### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/lang-spec#3]
Will this get a separate Discord, or occupy part of the TwinBasic/TwinBasic Discord? 
https://github.com/twinbasic/twinbasic/discussions/629

**Comment by WaynePhillipsEA** [comment]
It will be a separate channel on the usual discord server, as of tomorrow.  Thanks.

**Comment by WaynePhillipsEA** [comment]
The discord channel webhook is now active.  Thanks.
